Added hide transform policy to exclude sensitive or private fields
chiselstrike/chiselstrike pull request #1486
Opened 2022-06-28 06:41 UTC by notTJ

Added hide transform policy to exclude sensitive or private fields from the returning json object

2022-06-28 06:50 UTC, notTJ commented
I have read the CLA Document and I hereby sign the CLA

2022-06-28 06:51 UTC, notTJ commented
recheck

2022-06-28 10:24 UTC, dekimir requested changes
Looks good, I just have two suggestions.

2022-06-28 10:24 UTC, dekimir commented on server/src/policies.rs
> +                    Some("hide") => {
To avoid confusion with another [proposed](https://chiselstrike.notion.site/New-Policy-Language-for-ChiselStrike-f1720f065a8d4220a113590fd868f7cc) "hide" policy, may I suggest renaming this?  Perhaps "omit" or "omit_field"?

2022-06-28 10:24 UTC, dekimir commented on server/src/datastore/query.rs
> +            let field = builder.make_scalar_field(&field, ty.backing_table(), None, false);
`false` isn't very readable here.  Instead of a Boolean, I'd use an enum for this, like in these examples:
https://github.com/chiselstrike/chiselstrike/blob/8c7903548e0198d0ded4b03243e3b894b6d4503e/server/src/types.rs#L670
https://github.com/chiselstrike/chiselstrike/blob/8c7903548e0198d0ded4b03243e3b894b6d4503e/server/src/server.rs#L332-L333

2022-06-28 16:57 UTC, notTJ commented on server/src/datastore/query.rs
> +            let field = builder.make_scalar_field(&field, ty.backing_table(), None, false);
I added a new enum "KeepOrOmitField", changed query field property name is "keep_or_omit". Are these names ok?

2022-06-28 17:05 UTC, notTJ commented on server/src/policies.rs
> +    pub(crate) omit: HashSet<String>,
Would there be any reason we may specify an additional "Keep" transform, overriding a field which would otherwise be omitted? This could be a hashmap of <String, KeepOrOmitField>. I'm kind of wondering if there's a better name than just omit... "omitted_fields"?

2022-06-28 19:23 UTC, dekimir submitted a review, later dismissed
This is good enough for now.  I'll create a follow-up with tests and documentation.  If that reveals any problems, we'll fix them in stride.

2022-06-28 19:23 UTC, dekimir commented on server/src/policies.rs
> +    pub(crate) omit: HashSet<String>,
> Would there be any reason we may specify an additional "Keep" transform in the new policy language? It would include a field which would otherwise be omitted. This could be a hashmap of <String, KeepOrOmitField>.

That would make conflicting policies possible, right?  We'd need to specify how those conflicts are resolved.  Sounds complex.  I'd avoid that until it's deemed necessary by enough potential users.

> I'm also wondering if there's a better name than just omit... "omitted_fields"?

Yes, that's better.  But it can be a follow-up.

2022-06-28 21:59 UTC, glommer commented
hey there! FYI: CI are not passing, because we enforce coding style and clean linters.

Click "details" to see what exactly is wrong, but running `cargo fmt --all` and `cargo clippy` should fix it!

2022-06-29 14:55 UTC, dekimir commented
@notTJ looks like you still need to run `cargo clippy`:
https://github.com/chiselstrike/chiselstrike/runs/7114021755?check_suite_focus=true#step:14:424

2022-06-29 21:32 UTC, notTJ commented
> 

my bad I thought it worked like fmt --all, it should pass now

2022-06-29 23:32 UTC, glommer approved these changes

2022-06-29 23:32 UTC, glommer commented
Thanks!!!

2022-06-29 23:33 UTC, merged