Introduce `Entity` type covering Custom entity type and Auth types.
chiselstrike/chiselstrike pull request #1489
Opened 2022-06-28 10:10 UTC by BearLemma

This PR aims to make our type system more expressive and paves a way for extended typing support (`List`, `Array`, etc.)

There are multiple patches so reviewers are advised to go patch by patch. 
First thing this PR does is it introduces `Type::Entity(Entity)` and standalone `enum Entity {Auth, Custom}` types and makes amendments where necessary for the code to compile. 
Then it renames `add_builtin_object_type` -> `add_auth_type` and `add_type` -> `add_custom_type`.
Finally it brings home the idea and removes the `is_auth` field from `ObjectType` in favor of `Entity::is_auth` convenience method.

2022-06-28 10:38 UTC, dekimir requested changes
I don't understand how adding Primitive is related to singling out Auth types.  I also don't know what the alternative to primitive types is.  (For example: the alternative to scalar types is entities, and the alternative to builtin types is user-defined ones.)  Perhaps it's just a matter of explaining it in the commit message?

2022-06-28 10:38 UTC, dekimir commented on server/src/deno.rs
>          if ty.is_auth() && !is_auth_path(&c.api_version, &c.path) {
It feels like `Type::is_auth` should be affected by this change, yet it isn't.

2022-06-29 05:37 UTC, dekimir approved these changes
Approving to allow progress on List fields.  But I'm not convinced that separating auth types into their own enum elements is well-advised; they're more similar than different, and the separation doesn't extend to their ObjectType representations (eg: `get_auth_user_type()` looks up `AuthUser` by its name, even after we made it a unique known enum).  I'd like to see that commit reverted one day.

I also dislike the ambiguous and vague name "primitive".  These are really "storage" or "storable" types.

2022-06-29 07:59 UTC, MarinPostma commented on server/src/types.rs
> +
nitpick: I don't think that these method (along with `lookup_type_primitive`) are very helpful. Calling the type counterpart + `.primitive()` is a lot more explicit to me, since this `type`-`primitive` thing is already quite confusing

2022-06-30 04:12 UTC, dekimir approved these changes
Very nice job of using digestible, logical commits! Let's always do that. :D

2022-06-30 04:12 UTC, merged