Adding installation instructions for node.js into WSL
chiselstrike/chiselstrike pull request #1502
Opened 2022-06-30 11:37 UTC by NickHodges

2022-06-30 11:38 UTC, NickHodges commented
I have read the CLA Document and I hereby sign the CLA

2022-06-30 14:26 UTC, dekimir requested changes
Thank you @NickHodges!  This looks good, just one nitpick.

2022-06-30 18:40 UTC, NickHodges commented
Removing 'bash' as per discussion

2022-07-01 03:19 UTC, dekimir approved these changes

2022-07-01 03:19 UTC, merged