api improvements: allow users to return arbitrary types
chiselstrike/chiselstrike pull request #1534
Opened 2022-07-07 19:54 UTC by glommer

We mandate a Response to be returned, meaning that users have to do
returnFromJson, or in other ways construct responses.

However in many cases, specialized endpoints want to return well
defined things like an array of models, a model, or even strings.

Allow that to happen, by converting to a Response internally.
This is a major UX boost that allow us to craft much shorter endpoints

2022-07-08 04:15 UTC, dekimir requested changes

2022-07-08 04:15 UTC, dekimir commented on docusaurus/docs/Intro/endpoints.md
> +Optionally, your function can that take as a parameter a `ChiselRequest` or its parent class [Request](https://developer.mozilla.org/en-US/docs/Web/API/Request) with a few convenience fields added. I
With "or its parent class" this now doesn't make sense.  It reads like the "few convenience fields" are added to the function, not to `ChiselRequest`.

2022-07-08 04:15 UTC, dekimir commented on docusaurus/docs/Intro/endpoints.md
> +Finally, notice how in the cases where we want to return a `Response`, we can either return a standard `Response` but also the convenience method
I've heard of "either/or" but not of "either/but also". :p

2022-07-08 04:15 UTC, dekimir commented on cli/tests/lit/return.deno
> +# CHECK: HTTP/1.1 200 OK
This doesn't ensure that the endpoint returns nothing, as `lit` ignores extra output between CHECKs.  Perhaps you can tack on `&& echo UniqueString` to line 35 and CHECK for UniqueString here?

2022-07-11 18:42 UTC, glommer commented on docusaurus/docs/Intro/endpoints.md
> +Finally, notice how in the cases where we want to return a `Response`, we can either return a standard `Response` but also the convenience method
fixed

2022-07-11 19:57 UTC, glommer commented
@dekimir rebased

2022-07-12 23:58 UTC, dekimir approved these changes
I pushed two small doc fixes, and now this LGTM.

2022-07-13 00:42 UTC, merged