allow arbitrary defaults
chiselstrike/chiselstrike pull request #1600
Opened 2022-07-27 13:55 UTC by glommer

This PR allow us to write things like:

  a: number = Date.now()

in defaults.

We need surprisingly little to make this work, which makes me very
happy. Essentially, Entity.build() will already execute those functions,
so it works just fine.

We just need to make sure that the schema evolution works, which also
happen to work just fine: for complex expressions, we just treat them
as "no defaults". That makes sense, because if you have something like
"Date.now()", the behavior the user expects for things that didn't
exist before is not to retrofill with the current date...

So we allow adding mandatory types with literals and change the error
messages accordingly. Complex expressions behave like no-default.

We do miss the opportunity to allow things like "string".length and "1 +
2", which are not literals, but are pure and could be executed compile
time. However this is good for now, and we could in the future expand
chiselc to allow for those expressions to be parsed as literal defaults.

2022-07-27 14:19 UTC, honzasp commented
Hmm, maybe this fixes #1599 ?

2022-07-27 14:42 UTC, glommer commented
it does - as long as you don't expect those to behave as literal values (for that we'd need chiselc support)

2022-07-28 10:13 UTC, glommer commented on cli/src/ts.rs
> +            ModuleItem::Stmt(_) => {}
allowing non-class statements in the file.
They will be ignored by the parser, meaning we won't extract chisel information from it for the purpose of Model creation, but they are allowed in the file now

Allow us to write things like this:
```
function foo(): number { <== statement, ignored
    return Math.random()
}

export class Jan extends ChiselEntity {
   a: number = foo();
}
```

Note that we still compile that file in the project, so parse errors in the stament are still caught, but we don't look at it when doing the model.

2022-07-28 12:53 UTC, dekimir requested changes

2022-07-28 12:53 UTC, dekimir commented on cli/tests/lit/type-evolve.deno
> +# CHECK: Model defined: Defaults
Please add some `set` and `get` invocations here.  (Including checking for correct calculation of the new fields on previously existing entities.)

2022-07-28 12:53 UTC, dekimir commented on cli/tests/lit/type-evolve.deno
> +    c?: string = myFunction()
Please add a testcase for fields of entity type.

2022-07-28 12:57 UTC, dekimir commented on cli/src/ts.rs
> +            _ => Ok(None),
This basically introduces lenses through a side door.  I'm surprised that more work isn't required for lenses, even if we disallow auto-migration for mandatory fields.

2022-07-28 13:50 UTC, glommer commented on cli/src/ts.rs
> +            _ => Ok(None),
what does this have to do with lenses?

2022-07-28 13:59 UTC, glommer commented on cli/tests/lit/type-evolve.deno
> +# CHECK: Model defined: Defaults
What do you mean by "including checking for correct caltulation of the new fields on previously existing entities" ?
Together with the comment on lenses, I suspect you didn't fully read the commit description. Default fields that are not literals will not change existing fields.

2022-07-28 21:52 UTC, glommer commented on cli/tests/lit/type-evolve.deno
> +    c?: string = myFunction()
This works when I apply on a project:
```
export class Aux extends ChiselEntity {
    x: string = "bar";
}

export class Defaults extends ChiselEntity {
    a: number = "string".length
    b?: string = JSON.stringify({a: "test2"});
    c?: string = myFunction()
    d?: Aux = new Aux()
}
```

It doesn't work in the test and I have no idea why - it's driving me crazy. updates soon (I hope)

2022-07-28 22:19 UTC, dekimir commented on cli/src/ts.rs
> +            _ => Ok(None),
It tells you how to calculate a newly added field, which allows creating the new model version from the old one.

2022-07-28 22:22 UTC, dekimir commented on cli/tests/lit/type-evolve.deno
> +# CHECK: Model defined: Defaults
> What do you mean by "including checking for correct caltulation of the new fields on previously existing entities" ?

I mean invoke `/set` to create an entity with just field `a`, then extending model with fields `b` and `c`.  That one existing entity should then have `b` and `c` added correctly.

2022-07-28 22:23 UTC, dekimir commented on cli/tests/lit/type-evolve.deno
> +# CHECK: Model defined: Defaults
Hm, maybe not.  Because `b` and `c` are optional...

2022-07-28 22:50 UTC, glommer commented on cli/tests/lit/type-evolve.deno
> +# CHECK: Model defined: Defaults
that's not what this PR does, and what you're describing sounds like magic =p

Again, this is in the PR description: new objects will have that default. That means that those fields can only be added if they are optional (same evolution rules as before).

2022-07-28 22:50 UTC, glommer commented on cli/src/ts.rs
> +            _ => Ok(None),
this PR doesn't do this.

2022-07-28 23:39 UTC, glommer commented on cli/tests/lit/type-evolve.deno
> +    c?: string = myFunction()
FYI, found the issue.

The issue is that if in the same apply, we add a new model M1, and then add a property to an existing entity that is of type M1, it fails on type lookup: we'll lookup type M1 but it doesn't exist yet. It's a pre-existing problem and I just managed to reproduce without this PR, so I will for now just open an issue and move on.

2022-07-28 23:45 UTC, glommer commented on cli/tests/lit/type-evolve.deno
> +    c?: string = myFunction()
https://github.com/chiselstrike/chiselstrike/issues/1605

2022-07-29 00:10 UTC, glommer commented on cli/tests/lit/type-evolve.deno
> +    c?: string = myFunction()
I added a test that tests that we can have non-literal defaults for entities, but they have to be there from the start due to the issue above.

I don't think it is a priority to get to it now.

2022-07-29 01:31 UTC, glommer commented on cli/tests/lit/type-evolve.deno
> +    c?: string = myFunction()
lol, it's not a priority but I got annoyed and found the reason

2022-07-29 13:03 UTC, dekimir requested changes

2022-07-29 13:03 UTC, dekimir commented on server/src/datastore/meta/mod.rs
> +        // yet loaded.
Wasn't this (or a variant of it) solved by 897dbc3d??

2022-07-29 14:49 UTC, glommer commented on server/src/datastore/meta/mod.rs
> +        // yet loaded.
I explain that explicitly in the comment, although didn't mention the PR by number.
That only solves the case where you're adding all types at the same time.

We can't reuse that code easily either because it is implemented using the RPC messages with the textual description of the model. It's much easier to just retry load.

2022-07-29 14:58 UTC, glommer commented
@dekimir I updated this with your comments

2022-08-01 08:30 UTC, dekimir approved these changes

2022-08-01 08:30 UTC, merged

2022-08-01 09:38 UTC, dekimir commented on server/src/datastore/meta/mod.rs
> +        // yet loaded.
I suspect that retrying only once isn't enough, though I couldn't prove that with a simple example I ran.  But theoretically, if one failure depends on another failure (so neither is added to `ts` in the first `for` loop), then it is possible for the corresponding `load_type_fields()` in the second loop to error out, if failures are reprocessed in the wrong order.

2022-08-01 11:56 UTC, glommer commented on server/src/datastore/meta/mod.rs
> +        // yet loaded.
cycles could lead to that, but they are currently disallowed.

2022-08-01 13:22 UTC, dekimir commented on server/src/datastore/meta/mod.rs
> +        // yet loaded.
Cycles are a red herring, the failure chain only needs two links A > B > C for this to occur.  But it's still impossible, for another reason: one failure cannot chain on another.  A failure occurs only when an existing type adds a field of a new type.  All the new types are topo-sorted, so their field types always resolve on the first try.  Therefore, the chain stops right at the first link.