Refactor Deno code and implement new routing in chiseld
chiselstrike/chiselstrike pull request #1618
Opened 2022-08-04 08:23 UTC by honzasp

This is a work in progress. I will update this description when this becomes ready for review.

2022-08-11 13:07 UTC, honzasp commented
This PR is now ready for review. Pekka and Jenda, may I ask both of you to do the review? This is a big
change, so we need as many eyeballs as we can get to find any potential issues.

cc @penberg @BearLemma 

Please, **don't try to review the PR by scrolling through the Github diff**. You will be much happier if you
simply clone the branch into a temporary directory and use your IDE to read the code. Your IDE is much better
interface for reading and understanding code than Github!

I suggest that you start by reading PR description and studying the referenced files. When you gain some basic
understanding how things work, then you can use the Github diff as a guide to walk through the diff, switching
to you IDE whenever you encounter a bigger change.

Don't hesistate to write comments when something is unclear, even though it is correct. I would like to make
sure that the code is understandable, and I'm happy to add comments or refactor the code to make it more
clear.

This PR is still a draft, because I will add these changes:

1. Update the Docusaurus documentation to reflect the API changes.
2. Add integration tests that test the new functionality. I will also probably modify the new test framework
   using this experience.

But I think we should start the review now and not wait for these finishing touches.

Lastly, I'm open to applying parts of this PR separately, like we did in #1635: don't modifying this branch,
but applying the changes to `main` separately (so that they disappear from the diff of this PR).

*This is a big PR, but I'm confident that we can make this :)*

2022-08-12 12:04 UTC, penberg commented
@honzasp We use `pub(crate)` wherever possible _on purpose_ since day one because it allows us to detect unused code. Why are you switching over to `pub` everywhere?

2022-08-12 12:05 UTC, penberg commented
@honzasp Why is the `endpoints` directory renamed to `routes` in the tests? Are users also expected to do that for their projects?

2022-08-12 12:06 UTC, penberg commented
@honzasp The policy on copyright years is that we never update it on existing files.

2022-08-12 12:37 UTC, honzasp commented
> @honzasp We use `pub(crate)` wherever possible _on purpose_ since day one because it allows us to detect unused code. Why are you switching over to `pub` everywhere?

Dead code detection in Rust is smart: if you make an item `pub`, but don't export it from the crate and don't use it inside of the crate, it will be reported as dead code. So we can simply mark everyting `pub`, and use `pub(crate)` only at the top level of the crate, in `server/src/lib.rs`. The result is the same, but with less lexical noise.

2022-08-12 12:42 UTC, honzasp commented
> @honzasp Why is the `endpoints` directory renamed to `routes` in the tests? Are users also expected to do that for their projects?

Because the concept of an "endpoint" disappeared, so there is no reason to keep it in the directory names. Existing users don't have to do anything, because their `Chisel.toml` points to the `endpoints/` directory (and `endpoints` in `Chisel.toml` is now an alias for `routes`).

2022-08-12 12:45 UTC, honzasp commented
> @honzasp The policy on copyright years is that we never update it on existing files.

Oh, I'm an idiot, I should have checked this with you before changing this everywhere :( Does this policy also apply to files that were almost completely rewritten, like `server/src/server.rs`?

2022-08-12 12:58 UTC, penberg commented
> @honzasp Why is the `endpoints` directory renamed to `routes` in the tests? Are users also expected to do that for their projects?

To answer my own question: there's backward compatibility because most projects will have `Chisel.toml` with `endpoint` setting that `chiseld` knows to read in absence of `routes`.

However, I am not entirely convinced `routes` is the right name going forward. With the streaming support I am adding, there will be a `events` directory. In the future, I am hoping we will add support for periodic batch jobs in a `jobs` folder. So I kind of like `endpoints` because it hints towards "REST endpoints".

@honzasp what's your rationale for changing the directory name?

2022-08-12 17:40 UTC, honzasp commented
> @honzasp what's your rationale for changing the directory name?

The rationale is that the concept of an "endpoint" does not exist anymore and the structure that is defined by the files in that directory creates a "route map", whose entries are "routes". Using the name "endpoint" in just the directory name and nowhere else is weird.

The rationale for _that_ is that using a single name for one concept reduces confusion, which makes our users happier and more productive when using our services :)

(By the same reasoning, we should rename the "models" directory to "entities", because it contains definitions of entities and we don't use the name "model" anywhere else.)

2022-08-24 17:43 UTC, barbieri commented on api/src/crud.ts
> +        getAll?: boolean;
would you mind still keeping the behavior where the code could be customized? Like a function | boolean, this way any pre-post processing is easily done, the code here wouldn't become much more complex.

2022-08-24 17:44 UTC, barbieri commented on api/src/crud.ts
> +    async function getAll(req: ChiselRequest): Promise<Response> {
this function is huge, would you mind moving these all to toplevel functions that takes `entity` as first parameter? This way you can easily just bind the generic function to the current entity, if needed (ie: inside the `if` branch below).

2022-08-24 17:48 UTC, barbieri commented on api/src/crud.ts
> +        );
beaware this could modify the `id` as well, which would cause problems. I think it could also cause some issues with extra stuff being absorbed, when it shouldn't... just like there is `entity.build()`, maybe there should be be an entity.merge? or call `entity.build(await req.json())` in here?

2022-08-24 17:49 UTC, barbieri commented on api/src/crud.ts
> +            `Deleted entities matching ${new URL(req.url).search}`,
why not use the same `req.query`?

2022-08-24 17:51 UTC, barbieri commented on api/src/crud.ts
> -const defaultCrudMethods: CRUDMethods<ChiselEntity, GenericChiselEntityClass> =
in other words, I'd keep something like this one for the crud operations above.

2022-08-24 17:58 UTC, barbieri commented on api/src/crud.ts
> +        getAll?: boolean;
or to make code simpler, it could be `function | null`, this way null is handled as false/remove the method, you can spread the standard functions and you get everything for free (as the old code below):
 - if pass a custom function, it's used (overrides the spread)
 - if pass null, method is disabled (overrides the spread)
 - if nothing is passed, uses the default CRUD functions, declared as constant)

2022-08-24 18:02 UTC, barbieri commented on api/src/http.ts
> +    body: Uint8Array;
add `| undefined` here? Or at least declare 2 that would imply in the correct type, ex:

```ts
type HttpRequestCommon = {
    uri: string;
    headers: [string, string][];
    routingPath: string;
    userId: string | undefined;
};

type HttpRequestWithBody = HttpRequestCommon & {
    method: 'PUT' | 'PATCH';
    body: Uint8Array;
};

type HttpRequestWithoutBody = HttpRequestCommon & {
  method: 'GET' | 'HEAD' | 'DELETE';
};

type HttpRequest = HttpRequestWithBody | HttpRequestWithoutBody;
```

2022-08-24 18:03 UTC, barbieri commented on api/src/http.ts
> +            description = e.stack;
this is usually bad in production

2022-08-24 18:04 UTC, barbieri commented on api/src/http.ts
> +            description = e.stack;
nevermind, just goes to log... there is a TODO below.

2022-08-24 18:06 UTC, barbieri commented on api/src/http.ts
> +    return {
move this return inside `try` and make all of the variables `const`, so you avoid mistakes by any kind and code is shorter.

2022-08-24 18:07 UTC, barbieri commented on api/src/http.ts
> +    middlewares: Middleware[],
I'd change the signature to contain one more parameter `currentMiddlewareIndex` and then you can avoid creating/destroying the array on every step.

Your `if (middlewares.length == 0) {`  becomes `if (currentMiddlewareIndex === middlewares.length) {` and so on.

2022-08-24 18:08 UTC, barbieri commented on api/src/http.ts
> +    return { status, headers: [], body: new Uint8Array(0) };
move to constant?

2022-08-24 18:10 UTC, barbieri commented on api/src/http.ts
> +    return { status, headers: [], body: new Uint8Array(0) };
```ts
const emptyResponseBase = { headers: [], body: new Uint8Array(0) };

function emptyResponse(status: number): HttpResponse {
  return { status, ... emptyResponseBase };
}
```
or just propagate the shortcut to return a number and pass it along handling directly since it's common

2022-08-24 18:14 UTC, barbieri commented on api/src/kafka.ts
> +    topics: Record<string, EventHandler>;
given that the event encoding is not always well defined, there is protobuf/avro/... I'd promote a `ParseEvent` to first class here, sibling of `EventHandler`, you can provide UInt8Array directly to it and offer a pre-defined `fromJSON` version, making such case simpler as it doesn't require a schema (unlike protobuf/avro/...)

2022-08-24 18:22 UTC, barbieri commented on api/src/kafka.ts
> +    topics: Record<string, EventHandler>;
ie:
```ts
type ChiselEvent<K, V> = {
  key: K;
  value: V;
};
type ParseEvent<K, V> = (rawKey: UInt8Array, rawKey: UInt8Array) => ChiselEvent<K, V>;
type HandleEvent<K, V> = (event: ChiselEvent<K, V>) => Promise<void>;
type EventHandler<K, V> = {
  parser: ParseEvent<K, V>;
  handler: HandleEvent<K, V>;
};
```

and there is no need to have a `class` since it's better done as an actual JS object declared `as const`, so you get strict type checking, a given topic -> parser/handler.

2022-08-24 18:24 UTC, barbieri commented on api/src/kafka.ts
> +    };
then here would call `const chiselEvent  = topicMap[topic].parser(event.key, event.value)`

2022-08-24 18:26 UTC, barbieri commented on api/src/request.ts
> +    public user: AuthUser | undefined;
readonly fields? or at least flag the whole ChiselRequest as `Readonly<T>` before passing to the handlers

2022-08-24 18:32 UTC, barbieri commented on api/src/routing.ts
> +export type ResponseLike = Response | string | unknown;
like said, you could `| number` here and handle it as such.

2022-08-25 07:17 UTC, honzasp commented on api/src/crud.ts
> +        getAll?: boolean;
The idea was that if you want to customize a route, you will simply define it yourself. For example, if you wanted to customize the `PUT /:id` route, you would say something like:

```
crud(Entity, {put: false}) // don't generate the default `PUT /:id` route...
    .put('/:id', async function (req) { ... }) // but define it yourself
```

Do you think this makes sense?

The problem with this approach is that you as the user don't have access to the builtin CRUD functionality in `fetchEntitiesCrud` and `deleteEntitiesCrud`. We can resolve this in multiple ways, for example by simply `export`-ing these functions, but I wanted to start simple and add the functionality gradually.

2022-08-25 07:27 UTC, honzasp commented on api/src/crud.ts
> +    async function getAll(req: ChiselRequest): Promise<Response> {
I decided to keep the handler functions like `getAll` as closures in the `crud()` function, because they all use `entity` and `createResponse` from the scope of `crud()`. If they were hoisted to the top level, the code would look something like:

```typescript
async function getOne<
    T extends ChiselEntity,
    E extends ChiselEntityClass<T>,
>(
    entity: E,
    createResponse: CRUDCreateResponse,
    req: ChiselRequest,
): Promise<Response> {
    ...
}

// and inside crud()
routeMap.get("/:id", (req) => getOne(entity, createResponse, req))
```

I'm not sure whether this would be better than the current code; what would be the reasons for that? Or could we perhaps achieve that objective in more compact way?

2022-08-25 07:33 UTC, honzasp commented on api/src/crud.ts
> +        );
Yeah, I completely agree that this is very shady, I simply copied this code from the previous CRUD implementation. Note that `entity.build()` also calls `mergeDeep()` in exactly the same way! The problem is that we have no idea what are the properties of `entity` and their types. I'm not sure whether there is an easy solution, other than a major redesign of the data model API.

2022-08-25 07:37 UTC, honzasp commented on api/src/crud.ts
> +            `Deleted entities matching ${new URL(req.url).search}`,
Ah, good catch! I'll replace it with `req.query.toString()` :)

2022-08-25 07:42 UTC, honzasp commented on api/src/http.ts
> +    body: Uint8Array;
Hmm, what would be the motivation for this? When the request has no body, `HttpRequest.body` is simply empty. (Technically, an HTTP request always has a body, even though it should be empty for some methods.)

(Note that this type is passed to JavaScript from Rust, so this type is the JS representation of `HttpRequest` from `server/src/http.rs`.)

2022-08-25 07:48 UTC, honzasp commented on api/src/http.ts
> +    return {
Ok, why not; there used to be more code between the `try` statement and the `return` statement, but the structure no longer makes sense when this code is removed.

2022-08-25 07:53 UTC, honzasp commented on api/src/http.ts
> +    middlewares: Middleware[],
Ok; I wrote the code in recursive Haskell-ish style in an attempt to make it as clear as possible, but your version with explicit index is probably better :)

2022-08-25 07:56 UTC, honzasp commented on api/src/http.ts
> +    return { status, headers: [], body: new Uint8Array(0) };
What would be the reason to use `{ status: 500, ... emptyResposeBase }` instead of `emptyResponse(500)`? Are you concerned with the overhead of the function call and the two allocations?

2022-08-25 08:05 UTC, honzasp commented on api/src/kafka.ts
> +    topics: Record<string, EventHandler>;
The event handling was introduced in Pekka's PR #1634, in this PR I just want to reimplement the same functionality without modifying it or introducing new features (this PR is already huge!).

However, I agree that the current support for Kafka event consuming is very rudimentary (it is just a proof of concept, anyway). We should definitely provide some way to at least parse the `ArrayBuffer` as JSON, though I would prefer to simply provide a function `(ArrayBuffer) -> JSONValue` rather than coupling the parsing of bytes to the dispatch of events.

I'm not sure I understand your proposed API: do you want the event handlers in `events/` to export the `EventHandler<>` type, something like this?

```typescript
export default {
    parser: eventJsonParser,
    handler: async function (event: ChiselEvent<JSONValue, JSONValue>) {
        ...
    },
}
```

2022-08-25 08:08 UTC, honzasp commented on api/src/kafka.ts
> +    topics: Record<string, EventHandler>;
The reason why I use a `TopicMap` class with a single property of type `Record<string, EventHandler>`, instead of using `Record<string, EventHandler>` directly, is to maintain the close analogy with `RouteMap`.

2022-08-25 08:13 UTC, honzasp commented on api/src/request.ts
> +    public user: AuthUser | undefined;
Ah, this is a good idea :) But we may keep the option for the user to modify the `ChiselRequest`, for example in middlewares. Maybe we should ask Jenda (@BearLemma) for his opinion?

2022-08-25 08:16 UTC, honzasp commented on api/src/routing.ts
> +export type ResponseLike = Response | string | unknown;
You mean to replace the use of `emptyResponse()` in `handleHttpRequest()` in `http.ts`? Note that `handleHttpRequest` returns a `HttpResponse` which is passed directly to Rust.

The `ResponseLike` type is used as a return type of the user-defined handler. We _do_ allow to return a number, but the semantics is that we call `responseFromJson` to convert it to a JSON response with status 200.

2022-08-25 08:45 UTC, honzasp commented on api/src/request.ts
> +    public user: AuthUser | undefined;
We decided that there is no good reason for the user to modify these properties, so `readonly` be it :) (Also, we can always lift the restriction later.)

2022-08-25 09:01 UTC, honzasp commented
Thanks Gustavo for your review, I applied your suggestions in the latest commit :) I left replies where I would like some clarifications, so we can continue the discussion in the threads.
cc @barbieri

2022-08-25 14:19 UTC, dekimir commented on api/src/crud.ts
> +        getAll?: boolean;
Whatever you decide, please also update the [documentation](https://github.com/chiselstrike/chiselstrike/blob/791fea8d22be8912f8ad788820cf312bba8fd38d/docusaurus/docs/Intro/routes.md?plain=1#L18).

2022-08-26 13:48 UTC, barbieri commented on api/src/crud.ts
> +        getAll?: boolean;
@honzasp ok, makes sense... I think the other way is more "standard" as you get the paths and all defined, just need to do some extra logic/validation.

But your approach also has some advantages, since you don't get the paths and all, you can do whatever you want, that is more flexible.

2022-08-26 13:49 UTC, barbieri commented on api/src/crud.ts
> +    async function getAll(req: ChiselRequest): Promise<Response> {
your code would be smaller, did grew too big. You can get the "binding" either as you wrote or by using `fn.bind()` (single line)

2022-08-26 13:54 UTC, barbieri commented on api/src/crud.ts
> +        );
yeah, I saw the old ("suspicious") code, but since much is changing, I'd fix it as well at least by using `build()`.

If `build()` is broken we can fix it later, but we should be doing a safe approach in there, either going back to the Rust part where it knows the properties + types, either by generating some json schema and using Ajv.validate with coerce/removeAdditionalProperties (and then you can also generate the coreapi/swagger)...

TypeORM will use TypeScript annotations and metadata to get the columns (they force us to `@Column`), but maybe going back to Rust you can get the AST the same way you control what goes to the DB.

So `mergeDeep` per see is okay, the issue is not checking what was received in `req.json()`.

2022-08-26 13:56 UTC, barbieri commented on api/src/http.ts
> +    body: Uint8Array;
with the approach I said you can force TS to hint you, if you:

```ts
if (req.method === 'GET') {
  req.body // errors, since it doesn't exist
}
if (req.method === 'POST') {
  req.body // is always a string
}
```

if you want to force it to be `undefined`, just change the `HttpRequestWithoutBody` to include `body: undefined`. This way, if you ever use `req.body` the TSC will warn you "this may be undefined".

If you ALWAYS use `body: string | undefined` then in methods you KNOW there will be a body, you still need to check it... which is an usability issue.

2022-08-26 13:58 UTC, barbieri commented on api/src/http.ts
> +    body: Uint8Array;
https://www.typescriptlang.org/docs/handbook/2/narrowing.html#discriminated-unions

2022-08-26 14:00 UTC, barbieri commented on api/src/http.ts
> +    return { status, headers: [], body: new Uint8Array(0) };
yeah, you don't need to keep doing the allocations... but my personal preference is to handle `number` just like you handle `string` as a first class citizen, then it can go smooth, including user's code :-)

2022-08-26 14:09 UTC, barbieri commented on api/src/kafka.ts
> +    topics: Record<string, EventHandler>;
yes, you'd export that, BUT you should be linking the types in a way... it's better if you can get TSC to help instead of `JSONValue`.

For instance, if we can use ajv + JSONSchema you can even infer the typescript type from it, see https://www.fastify.io/docs/latest/Reference/TypeScript/#fastify-type-providers or even our own https://github.com/profusion/json-schema-to-typescript-definitions/

this way you get the type expected in that message.

As for `RouteMap`, yeah... I didn't comment on that one, but definitely that one could as well be a single object mapping stuff that is passed along. The actual "compilation" of stuff can happen as user-site, with the whole tree at hand. Ie you keep passing `type RouteMap = { [path: string]: Handler | RouteMap }`, then when you'll create your dispatcher you build the hierarchy... for example you could concatenate all the paths and use an object or `Map`, or you could even split the path and walk parts. In other words, it would be much simpler to use (less `map.route(xxx)`) and possibly more efficient so you're getting the whole tree at once at the end and can process the info in one go.

2022-08-26 14:37 UTC, honzasp commented on api/src/http.ts
> +    body: Uint8Array;
But I don't think we would get any type safety that way, because we don't use the `HttpRequest` type too much, we simply convert it to `ChiselRequest`. In fact, the `body` property is always here even for GET and HEAD, it just happens to be empty most of the time.

2022-08-30 15:12 UTC, honzasp commented on api/src/routing.ts
> +export type ResponseLike = Response | string | unknown;
I understand the point here, but it would be quite massive breaking change. Folks, what do you think? Should `return 404` return an empty response with status 404 instead of a JSON response saying `404`? @BearLemma @penberg @dekimir

2022-08-30 15:14 UTC, honzasp commented on api/src/crud.ts
> +        );
So what you are proposing is to do here is the following:
```
const orig = await entity.findOne(...);
mergeDeep(orig, await req.json());
const updated = entity.build(orig);
await updated.save();
```
Is that correct?

2022-08-31 14:52 UTC, CodingDoug commented on api/src/http.ts
> +        return emptyResponse(404);
I've noticed that throughout this file (and possibly elsewhere) there are a bunch of hard-coded HTTP codes that could probably be replaced by symbols that are more readable and less prone to typos.

2022-08-31 15:07 UTC, dekimir requested changes

2022-08-31 20:21 UTC, dekimir commented on api/src/routing.ts
> +export type ResponseLike = Response | string | unknown;
I think `return 404` is much more confusing and complicated to explain than `return emptyResponse(404)`.  The convenience is not worth the complexity.

2022-09-01 01:17 UTC, dekimir commented on api/src/crud.ts
> + * Put this in the file 'endpoints/comments.ts':
`endpoints` or `routes`?

2022-09-01 01:29 UTC, dekimir commented on api/src/crud.ts
> +        getAll?: boolean;
```
crud(Entity, {put: false}) // don't generate the default `PUT /:id` route...
    .put('/:id', async function (req) { ... }) // but define it yourself
```
Why force the user to say `put` twice?  Can we have `crud(Entity).put('/:id/', ...)`?  The very existence of `.put()` means a custom PUT route replaces the default CRUD one.

2022-09-01 02:25 UTC, dekimir commented on api/src/crud.ts
> +    async function getAll(req: ChiselRequest): Promise<Response> {
I think this is fine as is for now.  @barbieri if you feel like it, prepare a follow up that breaks the function down into parts, and we'll consider it separately.

2022-09-01 02:29 UTC, dekimir commented on api/src/crud.ts
> +        );
Please don't add any more "fixes" to this huge PR.  Reusing existing code is preferable; we'll fix it later.

2022-09-01 03:32 UTC, dekimir commented on api/src/routing.ts
> +    | Record<string, Handler>
Please explain what the `string` is.

2022-09-01 11:05 UTC, honzasp commented on api/src/http.ts
> +        return emptyResponse(404);
Good point, fixed! :)

2022-09-01 11:06 UTC, honzasp commented on api/src/run.ts
> +// handle HTTP requests)
I added a comment.

2022-09-01 11:48 UTC, honzasp commented on api/src/routing.ts
> +    | Record<string, Handler>
It was this feature:
https://www.notion.so/chiselstrike/Routing-afbeb5a48dda47a28f919f5a7165f387#75745f4d44ff4fb597f4f394d8414c6e

But I decided to remove it, it does not make any sense.

2022-09-01 12:39 UTC, 7flash approved these changes
__
[![sema-logo](https://app.semasoftware.com/img/sema-tray-logo.gif)](https://semasoftware.com/gh) &nbsp;**Summary:** :trophy: This code is awesome

2022-09-01 12:39 UTC, 7flash submitted a review, later dismissed

2022-09-02 10:05 UTC, honzasp commented on server/src/datastore/meta/mod.rs
> +            sqlx::query("SELECT url, code FROM modules WHERE version = $1").bind(version_id);
Yes, the `modules` table will be automatically created by the code in `server/src/datastore/meta/schema.rs`.

2022-09-02 10:05 UTC, honzasp commented on server/src/datastore/dbconn.rs
> +// SPDX-FileCopyrightText: © 2022 ChiselStrike <info@chiselstrike.com>
It's just me being too eager, I will revert these changes.

2022-09-05 13:34 UTC, honzasp commented
I reverted the new CRUD from this branch, the changes now live on another branch:
https://github.com/honzasp/chiselstrike/pull/1

2022-09-07 05:12 UTC, dekimir requested changes

2022-09-07 05:12 UTC, dekimir commented on server/src/worker.rs
> +    pub job_rx: Rc<RefCell<mpsc::Receiver<VersionJob>>>,
Why an `Rc`?  Doesn't each WorkerState get its dedicated receiver, separate from all others?  That's how I interpret the worker-spawning loop in `version::run()`.

2022-09-07 08:11 UTC, honzasp commented on api/src/http.ts
> +    // note that this means that we can only handle a single request at a time!
This problem runs much deeper than this function, it is inherent to the current design of our data layer (or, rather, lack of design).

2022-09-07 08:13 UTC, honzasp commented on server/src/ops/job.rs
> +        // yes, we really *do* want to hold a `RefMut` across `.await` ...
`RefMut`

2022-09-07 08:19 UTC, honzasp commented on server/src/ops/job.rs
> +            // ... if somebody else tries to borrow this `RefCell` while we are `.await`-ing, they will
Correct

2022-09-07 08:21 UTC, honzasp commented on server/src/worker.rs
> +    /// We can get away with `Rc<RefCell<>>`, because the worker runs on a single thread.
Because the `Arc<Version>`-s _are_ shared between threads:
1. The `Arc<Version>` is accessed from multiple workers
2. The `Arc<Version>` is accessed from HTTP and other "server-wide" code (that's why it needs to be stored in the `Trunk`)

2022-09-07 08:24 UTC, honzasp commented on server/src/version.rs
> +        let (job_tx, job_rx) = mpsc::channel(1);
This _shadows_ the variable declaration from line 79 (not line 65, which is in a different function). The reason is simply that I was lazy and overloaded the name `job_rx` for the channel that receives jobs for the version and for one particular worker. I will rename the variable to make this more clear.

2022-09-07 08:27 UTC, honzasp commented on server/src/version.rs
> +        let (job_tx, job_rx) = mpsc::channel(1);
The same applies to `ready_{tx,rx}`.

2022-09-07 08:46 UTC, honzasp commented on server/src/worker.rs
> +    pub job_rx: Rc<RefCell<mpsc::Receiver<VersionJob>>>,
The `Rc` is necessary for the `op_chisel_accept_job()`: I need to hold the `RefMut<mpsc::Receiver>` that I borrowed from `RefCell<mpsc::Receiver>` across await, so I need to hold a reference to the `RefCell` itself across await.

If the `RefCell<mpsc::Receiver>` was stored directly in the `WorkerState`, that would mean that I would have to hold the `Ref<WorkerState>` borrowed from the `deno_core::OpState` across the await too, so any other `op` that tried to access the `WorkerState` would fail.

---

In more detail:

Without the `Rc`, the "borrow chain" in `op_chisel_accept_job` would look like this:
- `&mut mpsc::Receiver` is mut-borrowed in `job_rx.recv().await` from
- `RefMut<mpsc::Receiver>` which is `RefCell.borrow_mut()`-borrowed in `match job_rx.try_borrow_mut() {` from
- `&RefCell<mpsc::Receiver>` which is passed to `recv_job()` and borrowed from
- `&WorkerState` which is borrowed from
- `Ref<WorkerState>` which is `RefCell.borrow()`-borrowed from
- `&deno_core::OpState` which is `RefCell.borrow()`-borrowed from
- `Rc<RefCell<deno_core::OpState>>` which is passed into `op_chisel_accept_job()`

So we would need to hold multiple `Ref`-s across the await, and any other op that would try to borrow the `OpState` or the `WorkerState` would fail.

But with `Rc<RefCell<mpsc::Receiver>>`, the "borrow chain" looks like this:
- `&mut mpsc::Receiver` is mut-borrowed in `job_rx.recv().await` from
- `RefMut<mpsc::Receiver>` which is `RefCell.borrow_mut()`-borrowed in `match job_rx.try_borrow_mut() {` from
- `&RefCell<mpsc::Receiver>` which is passed to `recv_job()` and borrowed from
- `Rc<RefCell<_>>` which we have _cloned_ into a local variable `job_rx` in `op_chisel_accept_job()`.

Thus, the `Rc` allows us to end the borrow chain before it reaches the `OpState`, so we don't have to keep any borrows from `OpState` alive across the await.

2022-09-07 16:44 UTC, dekimir commented on api/src/http.ts
> +    // note that this means that we can only handle a single request at a time!
But this function's blurb is an ideal place to warn all readers of this problem.  Anyone thinking about handling requests will naturally look to `handleHttpRequest()`.  Seeing a warning comment right up top lowers the risk of a nasty bug in the future.

2022-09-07 16:44 UTC, dekimir commented on server/src/worker.rs
> +    /// We can get away with `Rc<RefCell<>>`, because the worker runs on a single thread.
Ok.

2022-09-07 16:47 UTC, dekimir commented on server/src/version.rs
> +        let (job_tx, job_rx) = mpsc::channel(1);
Ah, OK.  Sorry, I guess I was blind to the `let` part. :smiley:

2022-09-07 17:05 UTC, dekimir commented on server/src/worker.rs
> +    pub job_rx: Rc<RefCell<mpsc::Receiver<VersionJob>>>,
OK, but why must `WorkerState` hold on to its copy?  Can we just move the `Receiver` out of `WorkerState` while we need it, then move it back in when we're finished?

2022-09-07 17:50 UTC, dekimir commented on server/src/version.rs
> +            if job_txs[worker_i].send(job).await.is_err() {
Come to think of it, how does this code know that `worker_i` has finished the previous request?

2022-09-07 18:08 UTC, honzasp commented on api/src/http.ts
> +    // note that this means that we can only handle a single request at a time!
Well, `handleKafkaEvent` has the same problem; perhaps I should add the comment to `run.ts`?

2022-09-07 18:12 UTC, honzasp commented on server/src/worker.rs
> +    pub job_rx: Rc<RefCell<mpsc::Receiver<VersionJob>>>,
Hohoho, that's a good idea! :) This would elegantly get rid of all the tricky code, and the overhead of moving the `mpsc::Receiver` back and forth is negligible in this case. I'll look at that in more detail and change the code, if there is not some problem that I cannot see right now.

2022-09-07 18:14 UTC, honzasp commented on server/src/version.rs
> +            if job_txs[worker_i].send(job).await.is_err() {
It does not, if the `job_txs[worker_i]` channel is already full, this call will block (there is an `.await`). Of course, this naive round-robin is rather dumb and could certainly be improved, but I went for the simplest solution now and left the optimizations as future work, to avoid introducing extra complexity to this PR :)

2022-09-07 22:41 UTC, dekimir commented on server/src/version.rs
> +            if job_txs[worker_i].send(job).await.is_err() {
Good! :)  But that makes it essential for the channel to be of size 1.  I'll leave a comment in version.rs to ask for an explanation there.

2022-09-07 22:45 UTC, dekimir commented on server/src/version.rs
> +        let (job_tx, job_rx) = mpsc::channel(1);
Please add a comment here saying that size must be 1 or rivers of blood will flow (otherwise a worker will attempt to interleave handling of multiple requests and mess up horribly and unpredictably).

2022-09-07 22:48 UTC, dekimir commented on api/src/http.ts
> +    // note that this means that we can only handle a single request at a time!
I'd start with big warnings atop `handleHttpRequest` and `handleKafkaEvent`.  Then you can additionally comment in run.ts saying "please never send me the next request before I complete the current one".

2022-09-08 07:06 UTC, honzasp commented on server/src/version.rs
> +            if job_txs[worker_i].send(job).await.is_err() {
Why would the size 1 be essential? It would work the same if the size was 2 or 10, the size of the channel affects only the number of jobs that can get buffered before `send()` blocks.

2022-09-08 07:10 UTC, honzasp commented on server/src/version.rs
> +        let (job_tx, job_rx) = mpsc::channel(1);
This is not true, the channel works as a queue: what is important is that the code in `run.ts` only handles a single job at a time, which is trivially true, because there is a simple `loop { accept job; handle job }` with no concurrency. The number of jobs potentially waiting in the channel to be accepted and handled is irrelevant. (In fact, I would prefer a "rendez-vous" channel of size 0, but Tokio unfortunately does not support that.)

2022-09-08 12:50 UTC, dekimir commented on server/src/version.rs
> +        let (job_tx, job_rx) = mpsc::channel(1);
> the code in `run.ts` only handles a single job at a time, which is trivially true, because there is a simple `loop { accept job; handle job }` with no concurrency.

I don't believe that's true.  Doesn't every `await` in that code (and there are three) create concurrency?  The runtime doesn't freeze and do nothing while waiting for a promise to resolve.

2022-09-08 16:58 UTC, dekimir commented on server/src/version.rs
> +        let (job_tx, job_rx) = mpsc::channel(1);
Actually, I take that back.  @MarinPostma reminds me that `await` is precisely what prevents concurrency here.  So you're right, the loop in `run.ts` uses carefully placed `await`s to ensure there's no interleaving even if the channel size is larger than 1.  And if someone accidentally forgets an `await` there in a future update, the compilation will likely fail.

OK, there's no need for a comment on channel size here.

2022-09-08 17:02 UTC, dekimir commented on api/src/run.ts
> +        const job = await opAsync(
OK, let's definitely add a comment here that interleaved calls to `op_chisel_accept_job` aren't allowed until the job completes, so never forget to `await` everywhere.

2022-09-08 17:05 UTC, dekimir commented on server/src/ops/job.rs
> +async fn op_chisel_accept_job(
Here, too: let's add a blurb that cautions against calling this function repeatedly without waiting for the job to complete.

2022-09-08 17:52 UTC, honzasp commented on server/src/ops/job.rs
> +async fn op_chisel_accept_job(
Ok, that's probably a good idea; but note that if somebody mistakenly does call the function repeatedly, nothing catastrophic will happen, they will simply get a (very descriptive) runtime error.

2022-09-08 17:55 UTC, honzasp commented on api/src/run.ts
> +        const job = await opAsync(
Well, this is not technically true: `op_chisel_accept_job` only requires that you won't call it multiple times before it returns, it does not care whether the job completed or not. If you try to start two concurrent jobs, you will get an error from `op_chilsel_begin_transaction`, because each job will try to begin the global transaction.

2022-09-08 17:56 UTC, honzasp commented on api/src/run.ts
> +        const job = await opAsync(
(To verify that `op_chisel_accept_job` is not called concurrently, the only conditions that need to be true are:
1. `run()` is only called once
2. `op_chisel_accept_job` is only called from `run()` and the call is immediately `await`-ed)

2022-09-09 09:28 UTC, honzasp commented
I think that I have addressed all issues brought up in review.

2022-09-09 11:25 UTC, dekimir requested changes
Just a couple more, before I forget...

2022-09-11 15:09 UTC, dekimir commented on server/src/trunk.rs
> +    /// NOTE: this sender cannot be stored in the `Version`, because the version terminates only
But doesn't Version happily hold all Workers' senders without facing this problem?  What's the difference?

And why doesn't Trunk spawn Versions, like Version spawns Workers?  Instead we have `server` and `rpc` spawning versions and immediately calling `trunk.add_version` on the result.

2022-09-11 15:09 UTC, dekimir commented on server/src/trunk.rs
> +pub async fn spawn() -> Result<(Trunk, TaskHandle<Result<()>>)> {
Can there be a Trunk without a task?  Can a Trunk have multiple tasks for it?  If not, I don't see why we separate the task from the Trunk.

And same goes for Version and Worker.

2022-09-11 15:09 UTC, dekimir commented on server/src/trunk.rs
> +        // should terminate on its own when all `Arc<Version>`s are dropped
This seems to contradict line 34.

2022-09-11 18:40 UTC, honzasp commented on server/src/trunk.rs
> +    /// NOTE: this sender cannot be stored in the `Version`, because the version terminates only
No, `Version` does not reference any sender, directly or indirectly.

The `job_task` task that runs as part of the "version task tree" owns the version job receiver and the worker job senders. When the version job sender is dropped, the `job_task` will terminate and the worker job senders will be dropped, so the worker job receivers will become closed and the workers will terminate.

During apply, we need to spawn a "canary" version to check whether the provided code is correct; this version must not be added to the `Trunk`, because it is not supposed to replace the current version.

However, as you mention elsewhere, we spawn versions and add them to trunk in at least three different places: it might be good idea to create a function that does this and make it a part of the `Trunk` code. I will investigate this after I'm back from the vacation.

2022-09-11 18:44 UTC, honzasp commented on server/src/trunk.rs
> +pub async fn spawn() -> Result<(Trunk, TaskHandle<Result<()>>)> {
This pattern is used in multiple places in the code (server, trunk, version, worker): there is a task that performs some work, and an object that contains state related to this work.

We cannot store the `TaskHandle` inside of the `Trunk`, because we need to store the `Trunk` in the `Server` structure, but we need to `.await` (consume) the task in `server::run()`.

2022-09-11 18:45 UTC, honzasp commented on server/src/trunk.rs
> +        // should terminate on its own when all `Arc<Version>`s are dropped
Good catch, I didn't update the comment when I updated the code.

2022-09-11 18:48 UTC, honzasp commented on server/src/server.rs
> +    start_chiselstrike_version(server.clone()).await?;
We don't have an explicit concept of "user" vs "internal" version; in fact, it seems to me that the `__chiselstrike` version is really a kludge, which is the reason why the code looks kludge-y. (Unclear code and unclear prose are both the result of unclear thinking.)

2022-09-12 05:08 UTC, dekimir commented on server/src/server.rs
> +    start_chiselstrike_version(server.clone()).await?;
We definitely have types and endpoints that the user never defined, so they go into a special version.  Maybe you don't want to call that "an explicit concept", but we do have that.  And that special version's name is arbitrary -- any name is OK, as long as it doesn't clash with the user's versions.  I question the decision to use that name here in this function, because the result is confusing -- are versions from line 53 somehow not ChiselStrike versions??  I agree about unclear code/prose (why must all types -- even builtins -- belong to a version?), but this naming decision reduces clarity further.  Can't we name these functions something better?

2022-09-12 05:28 UTC, dekimir commented on server/src/trunk.rs
> +    /// NOTE: this sender cannot be stored in the `Version`, because the version terminates only
> No, `Version` does not reference any sender, directly or indirectly.

Ah, I see: `version::run()` does, but not the `Version` struct.  I guess the difference is that `Trunk` has a simpler job than `Version`: it just needs to look up a version id and give the corresponding sender to the HTTP request handler.  `Version`, in contrast, has to distribute jobs to workers.

> During apply, we need to spawn a "canary" version to check whether the provided code is correct; this version must not be added to the `Trunk`, because it is not supposed to replace the current version.

I wonder if we truly need to _spawn_ a version just to check the code.  It doesn't sound right to create tasks you don't ever intend to activate.  Perhaps there should be common code at a finer granularity between code-check and actual spawning?

2022-09-12 05:40 UTC, dekimir commented on server/src/trunk.rs
> +pub async fn spawn() -> Result<(Trunk, TaskHandle<Result<()>>)> {
Is that to say that `Trunk` must outlive its task?

It's good that the same pattern is used everywhere, it makes it easier to read the code; but the pattern is open to misinterpretation -- the task and the state object are separate, even though they're clearly related in non-trivial ways.  We should describe that relation explicitly, either through design (preferably) or through comments.

Also, if these structs are state, why aren't they all named with a "State" suffix, like WorkerState is?  It feels like Server, Trunk, and Version are not a task's state but legit APIs on their own, with clients that don't care about the ongoing tasks.

2022-09-12 15:43 UTC, honzasp commented on server/src/trunk.rs
> +    /// NOTE: this sender cannot be stored in the `Version`, because the version terminates only
The canary version is the same as any other version, it is just not added into the `Trunk`. To check whether the code is correct, we need to spawn the Deno tasks and everything, so we cannot really simplify the spawning of canary versions too much.

I'm not sure what you mean by "activating" the tasks?

2022-09-12 15:53 UTC, honzasp commented on server/src/trunk.rs
> +pub async fn spawn() -> Result<(Trunk, TaskHandle<Result<()>>)> {
You are right, I'm not very consistent here, `Server` could as easily be named `ServerState`. I think that the confusion comes from the fact that we are used to object-oriented programming and objects that _do_ things. But objects are just data structures, the tasks are "doing things".

`Server` stores server-wide data structures and the server tasks perform the work of the server (such as receiving HTTP requests or running Deno), `Trunk` is a data structure that stores all active versions and their tasks, and the trunk task polls the version tasks, etc.

I'm not sure how we can describe the relation between the `Trunk` and the trunk task more explicitly than it is now, when both pieces of data are returned by `trunk::spawn`. Could you describe what exactly you find unclear, what confusion might arise?

2022-09-12 16:00 UTC, honzasp commented on server/src/server.rs
> +    start_chiselstrike_version(server.clone()).await?;
The versions from line 53 are ChiselStrike versions, but they are not `__chiselstrike` versions.

The concept of an "internal version" and "types and endpoints" that the user never defined are quite weird. Versions are completely independent in code and in data, _except_ that they use the same database for storing users and sessions. This "design decision" means that, for example, we cannot use SQLite for development versions and Postgres for production versions, because all versions must be in the same database!

2022-09-12 17:16 UTC, dekimir commented on server/src/server.rs
> +    start_chiselstrike_version(server.clone()).await?;
> The versions from line 53 are ChiselStrike versions, but they are not `__chiselstrike` versions.

... and the name `__chiselstrike` is arbitrary and inconsequential.  Please don't use it here like this, it's harmful to the reader's understanding and entirely unnecessary.  Use anything else: `internal`, `auth`, `universal`, `special`, `intrinsic`, `builtin` -- anything but `chiselstrike`.

> "types and endpoints" that the user never defined are quite weird. Versions are completely independent in code and in data, _except_ that they use the same database for storing users and sessions.

Agreed, and we can change that later.  But until we change it, let's please not confuse the reader any further.

2022-09-12 20:16 UTC, dekimir commented on server/src/trunk.rs
> +    /// NOTE: this sender cannot be stored in the `Version`, because the version terminates only
> I'm not sure what you mean by "activating" the tasks?

I mean tasks never receiving any jobs and getting dropped as soon as they signal they're ready.

2022-09-12 20:32 UTC, dekimir commented on server/src/trunk.rs
> +    /// NOTE: this sender cannot be stored in the `Version`, because the version terminates only
> To check whether the code is correct, we need to spawn the Deno tasks and everything

Tell me more about this.  Why isn't just compiling the module code enough to validate it?  Do we need to execute it to build a RouteMap?

2022-09-12 20:38 UTC, dekimir commented on server/src/trunk.rs
> +pub async fn spawn() -> Result<(Trunk, TaskHandle<Result<()>>)> {
> I'm not sure how we can describe the relation between the `Trunk` and the trunk task more explicitly than it is now, when both pieces of data are returned by `trunk::spawn`. Could you describe what exactly you find unclear, what confusion might arise?

Is a Trunk object allowed to have zero tasks?  How about multiple tasks?  Does a Trunk ever outlive its task or vice versa?  If I have a Trunk object and want to get to its task(s), how do I do that?  How do I do the opposite?

2022-09-12 20:51 UTC, dekimir commented on server/src/trunk.rs
> +pub async fn spawn() -> Result<(Trunk, TaskHandle<Result<()>>)> {
Actually, I'm noticing that `TrunkState` is a separate struct.  That's... complicated.  I don't think I understand the pattern you're talking about.

2022-09-13 07:07 UTC, honzasp commented on server/src/trunk.rs
> +    /// NOTE: this sender cannot be stored in the `Version`, because the version terminates only
Yes, just importing the modules would only check for syntax errors, initializing the modules and building the `RouteMap` catches muchmore errors.

2022-09-13 07:19 UTC, honzasp commented on server/src/trunk.rs
> +pub async fn spawn() -> Result<(Trunk, TaskHandle<Result<()>>)> {
In the case of `Trunk`, I had to introduce `TrunkState` because I need to wrap it in the `Arc<RwLock>`. I agree that the naming is not very consistent, do you have some suggestion for better naming?

> Is a Trunk object allowed to have zero tasks? How about multiple tasks?
> If I have a Trunk object and want to get to its task(s)

When you "spawn a trunk", you get a `Trunk` instance and a handle to the task. To be honest, it never even occured to me that the relationship would be unclear, and I still don't understand what you don't understand :)

> Can I move or drop a Trunk object while its task is active?

As you can see, the `Trunk` object is just a wrapper around `Arc<Mutex>`, so you can clone it and drop it as you wish, without affecting anything else.

> How do I deduce the task's state from a Trunk instance?

I don't understand this question. What does "deducing a task's state" mean and why would you want it?

> why does Trunk have methods?

The methods of the `Trunk` have methods to manipulate the `Trunk` data structure.

> Version, in fact, has two info objects: Version and VersionInfo

`VersionInfo` is a legacy struct whose meaning eludes me, but I didn't want to remove it to avoid being accused of making the PR too big.

2022-09-13 07:43 UTC, honzasp commented on server/src/trunk.rs
> +pub async fn spawn() -> Result<(Trunk, TaskHandle<Result<()>>)> {
I mean, you really don't understand how the code works, or you understand it but think that it is badly designed? If the former is true, maybe I should explain it more? If the latter, then I agree that the naming is inconsistent and I would welcome any suggestions for improvement.

2022-09-13 07:46 UTC, honzasp commented on server/src/trunk.rs
> +    /// NOTE: this sender cannot be stored in the `Version`, because the version terminates only
> I mean tasks never receiving any jobs and getting dropped as soon as they signal they're ready.

I see; why doesn't this sound right to you? Do you think that introducing extra code would be better?

2022-09-14 07:29 UTC, honzasp commented on server/src/server.rs
> +    let (ready_tx, _ready_rx) = oneshot::channel();
Unfortunately, I was not able to find a meaningful drying.

2022-09-16 15:34 UTC, dekimir commented on server/src/trunk.rs
> +    /// NOTE: this sender cannot be stored in the `Version`, because the version terminates only
After chatting in person, we agreed it's fine to validate modules by spawning a trial-balloon version and shutting it down as soon as it's ready to receive tasks.  This ensures the real spawning will also succeed, and it doesn't prevent future evolution of real spawning.

2022-09-16 15:35 UTC, dekimir commented on server/src/trunk.rs
> +pub async fn spawn() -> Result<(Trunk, TaskHandle<Result<()>>)> {
After chatting in person, we agreed this is a comment/doc issue and shouldn't hold up this PR.  We'll address it separately later.

2022-09-16 15:37 UTC, dekimir reviewed
LGTM.  (Not formally approving yet to prevent automerge.)

2022-09-21 15:36 UTC, penberg approved these changes

2022-09-21 15:54 UTC, merged