Policies: rename verbs to methods.
chiselstrike/chiselstrike pull request #1652
Opened 2022-08-17 12:01 UTC by BearLemma

Renaming verbs to methods as that seems more customary. (https://stackoverflow.com/a/49908515/1474847)

2022-08-17 12:03 UTC, penberg approved these changes
If @dekimir doesn't like this, we can revert.

2022-08-18 09:27 UTC, honzasp approved these changes

2022-08-18 13:32 UTC, glommer requested changes
this can no longer go in.
(and it is a great example of why we should be careful in the future with merges)

We now have a release, 0.12, in which users make reference to `verbs` in yaml and may be already using it.

We have to either live with "verbs", or change it so that both "verbs" and "methods" are accepted in the yaml file.

2022-08-18 16:29 UTC, penberg approved these changes

2022-08-18 16:33 UTC, honzasp commented
> (and it is a great example of why we should be careful in the future with merges)

Well, both Jenda and me had brought up this issue in that PR multiple times, Dejan explicitly decided to keep using "verb".

But I think it should be easy to retain backwards-compatibility by supporting both variants in YAML.

2022-08-19 06:02 UTC, merged