Introduce DataContext
chiselstrike/chiselstrike pull request #1805
Opened 2022-09-28 10:24 UTC by MarinPostma

In an effort to decouple the runtime from the data layer, this PR introduce the DataContext structure. The DataContext represents a transaction, and contains the data necessary for the data layer to carry on operations.

At the runtime layer, the JobContext is introduced. The JobContext spans the job lifetime, and should be used to store any data pertaining this job. This simplifies resources management.

2022-09-29 14:18 UTC, honzasp requested changes
I love these changes, they are definitely step in the right direction! :) But I think that the design needs another iteration.

The main problem is that the design couples the Deno layer and data layer too much together and overuses the concept of the "job". Instead of the "job context" (`JobInfo`/`JobContext`), it would be better if the concept of the "data context" was exposed directly to JS, and the concept of a "job" continued to be used only for what it was designed for: to pass a HTTP request or a Kafka event from Rust to JS.

There is no reason to couple data context to a job. Why couldn't we have multiple data contexts per job? Why couldn't we have a data context without a job?

One reason is that policies need information from the HTTP request for data-related operation. But the correct solution is to introduce a "policy context", which captures this information. The concept of a "policy context" also makes it obvious that policies assume that the data operations are only invoked from HTTP requests, but this is false: we now have Kafka event handlers, and we will likely add more kinds of jobs in the future (such as periodically-invoked cron jobs).

(Another way to think about the "policy context" is as a "capability" object that gives JS code the _permission_ to perform some subset of data operations. You then use this permission to get the actual transaction/"data context".)

---

I propose the following modifications:

- Expose the `DataContext` structure as a resource to JS; all data operations should take a reference to this resource (note that this makes it impossible to call a data operation without a data context, so it's not necessary to check for the presence of some "current data context", as you have to do in this PR).
- Create and close the data contexts from JS; this replaces the beginning and committing/rollbacking of transaction. There is no need to couple data context to job creation. (Some jobs don't need a data context, some jobs may need multiple data contexts.)
- Think hard about how policies should work with Kafka events, and then come up with a "policy context" which captures the information from an HTTP request or a Kafka event that is necessary to evaluate policies. Make sure that this "policy context" is generic enough (a good rule of thumb is, how could we extend the "policy context" for cron jobs?)
- Pass the "policy context" as a resource in the `AcceptedJob` structure from Rust to JS, and require it to create a new "data context".
- Data operations then have access to the "policy context" through the "data context" and can use it to evaluate policies.

2022-09-29 15:55 UTC, MarinPostma commented
@honzasp You are missing the bigger picture here. Let me address your points.
> Why couldn't we have multiple data contexts per job?

It is completely acceptable that a job has multiple DataContexts, just not possible to hold multiple contexts at the same time. Furthermore, even if you allowed it, then I see no issue with the current approach. Notice that allowing a job to accept multiple data contexts means that we also need to tie the objects to the data contexts they come from.

> One reason is that policies need information from the HTTP...

This is because the current policies are more or less stateless. They only need some information from the job, and that information is available from the beginning of the job. What you propose is that we have two separate resources, one for the policy context, and another for the current data context for the job (notice that these are already 2 resources that you need to manage). Now, the new policies are stateful. They cache some computation, mark some object dirty etc... In that sense, the logical lifespan of the `PolicyContext` is the `DataContext`, since some of the state held by the context is only valid in the context of the transaction it originates from.

FIY, the new policies do have a `PolicyContext`. It is created and passed to the `DataContext` at its creation, and having more design freedom, it is more decoupled.

**Please see the current inclusion of the `JobInfo` in the `DataContext`** as a hack, rather than a design decision. The scope of this PR is not to refactor legacy policies, and this appeared to be the least intrusive way to glue things together for now.

> The concept of a "policy context" also makes it obvious that policies assume that the data operations are only invoked from HTTP requests, but this is false:

I'm not sure I understand this part, is the `PolicyContext` a good thing or a bad thing? 😄 

> There is no need to couple data context to job creation. (Some jobs don't need a data context, and some jobs may need multiple data contexts.)
But that is not, the data context is created when a transaction is requested. When we have jobs that need multiple simultaneous DataContext, we'll accommodate the JobContext to do so. The only reason they are still tied is because of legacy policies, but again it is not the scope of this PR to rework that.

> Create and close the data contexts from JS; this replaces the beginning and committing/rollbacking of transactions. There is no need to couple data context to job creation. (Some jobs don't need a data context, and some jobs may need multiple data contexts.)

this is more or less what is happening now

> Pass the "policy context" as a resource in the AcceptedJob structure from Rust to JS, and require it to create a new "data context".

I guess this is where we really disagree on the essence of the design. One of my design goals is to minimize the number of resources that we need to manage. This is error-prone, and hard to debug. Hence the job context encloses all the resources for a job in one single resource and simplifies resource management. You may be able to reason about all the resources a job is using in its lifetime, when to deallocate them, and from which side (rust, or js) to do it, but unfortunately, I'm not as confident as you and thinking about how this code will age, I'd much rather refactor a rust struct than keep adding new resources to a job.

2022-09-29 16:05 UTC, MarinPostma commented on server/src/datastore/mod.rs
> +use crate::ops::job_context::JobInfo;
that's a hack, see my response. tldr, it's not the scope of this PR to refactor how policies work now. It is sufficiently easy to replace this with some policy context, since only the legacy policies rely on this.

2022-09-29 16:05 UTC, MarinPostma commented on server/src/datastore/engine.rs
> +    pub async fn create_transaction_context(
yes, i'm troubled by this name as well, but maybe `DataContext` is not the right name, maybe `TransactionContext` would be a better name?

2022-09-29 16:05 UTC, MarinPostma commented on api/src/run.ts
> +        }
this is terribly badly documented on deno's side...

what do you suggest? maybe rust should always be the one closing a resource?
In that case, the response op doesn't consume, and we call a teardown op here instead of closing.

2022-09-29 16:05 UTC, MarinPostma commented on api/src/run.ts
> +    | { type: "http"; request: HttpRequest; ctx: number }
👍

2022-09-29 16:20 UTC, MarinPostma commented
Also, notice that js is completely oblivious to what the ctxId is, for it is just some indirection to some context that ties together a bunch of syscall. Say implement a new thing, that is not a job, then it could have its own context, and it is a resource, and pass its id to js, and everything would work the same, as far as js is concerned.

2022-09-29 17:15 UTC, honzasp commented on server/src/datastore/mod.rs
> +use crate::ops::job_context::JobInfo;
Ok, makes sense! :)

2022-09-29 17:20 UTC, honzasp commented on api/src/run.ts
> +        }
I would make it the responsibility of each `if (job.type === X)` block to close the `job.ctx`. `job.type === "http"` closes the context using `op_chisel_http_respond`, and `job.type === "kafka"` can close it simply by using `Deno.core.close()` after `await handleKafkaEvent(...)`.

2022-09-29 17:25 UTC, honzasp commented on server/src/datastore/engine.rs
> +    pub async fn create_transaction_context(
I like the name "data context": it's the context passed to data layer, and the name is quite concise :)

I think that in the future, we might actually need to support a sequence of transaction in the same data context: let's say that in a single HTTP request, the user wants to do A, commit, and then do B. A and B should share the same entity objects and everything, so the "data context" should stay the same, but the transaction will change. This would mean that the concept of "data context" would no longer be equivalent to the concept of "transaction".

2022-09-29 17:28 UTC, honzasp commented on server/src/ops/job_context.rs
> +        Ok((info, ctx))
Fair enough; we could solve that by putting the transaction into an `Option` and replacing it with `None` on commit, but using `Rc::try_unwrap()` might also be an acceptable solution.

2022-09-30 08:43 UTC, MarinPostma commented on server/src/ops/job_context.rs
> +        Ok((info, ctx))
Actually, I rolled back to using the refcell-option thing, this also simplifies closing the resource, by handing this. duty to js.

2022-09-30 13:54 UTC, honzasp approved these changes
I want to reiterate: despite the length of my comments, this is really good work that significantly improves the server! :) And I'm looking forward to further improvements, especially the removal of `JobInfo` from `DataContext`.

2022-10-03 08:54 UTC, honzasp approved these changes

2022-10-03 08:54 UTC, merged