NextAuth.js adapter
chiselstrike/chiselstrike pull request #1837
Opened 2022-10-13 06:30 UTC by penberg

2022-10-13 13:32 UTC, barbieri submitted a review, later dismissed
I didn't re-review the lib/adapter part, but package wise looks good

2022-10-17 20:26 UTC, dekimir requested changes
This differs significantly from the existing adapter PR, and I'm not sure why.  Are all the changes really necessary?

2022-10-17 20:26 UTC, dekimir commented on packages/chiselstrike-next-auth/README.md
> +To use the adapter in your application, do the following:
"do" is ambiguous here.  Please explain which file this is and where it goes.

2022-10-17 20:26 UTC, dekimir commented on packages/chiselstrike-next-auth/README.md
> +    providers: [
This is irrelevant to the adapter.  I'd suggest replacing it with a placeholder.

2022-10-17 20:26 UTC, dekimir commented on packages/chiselstrike-next-auth/README.md
> +        secret: "1234",
Values here should be abstract.

2022-10-17 20:26 UTC, dekimir commented on packages/chiselstrike-next-auth/README.md
> +        url: "http://localhost:8080/__chiselstrike/auth/",
The adapter should add `__chiselstrike/auth` automatically, as this is an internal detail that can change.

2022-10-17 20:26 UTC, dekimir commented on packages/chiselstrike-next-auth/README.md
> +
Why did you drop the part about the `ChiselUID` header?

2022-10-17 20:26 UTC, dekimir commented on packages/chiselstrike-next-auth/jest.config.js
> +    // // Indicates whether the coverage information should be collected while executing the test
Let's remove these commented-out comments.  They're not helpful here.

2022-10-17 20:26 UTC, dekimir commented on packages/chiselstrike-next-auth/lib/adapter.ts
> +        async createUser(data) {
Why isn't the parameter typed?

2022-10-17 20:26 UTC, dekimir commented on packages/chiselstrike-next-auth/lib/adapter.ts
> +            return toUser(await response.json());
What if response status isn't OK?

2022-10-17 20:32 UTC, dekimir commented on packages/chiselstrike-next-auth/lib/adapter.ts
> +                method: "PUT",
This should be PATCH.

2022-10-17 20:39 UTC, dekimir commented on packages/chiselstrike-next-auth/lib/adapter.ts
> +    return toSession(sessions[0]);
This pattern (get `.results`, ensure `[0]` exists, return `[0]`) repeats at least four times.  Consider DRYing.

2022-10-18 06:15 UTC, penberg commented on packages/chiselstrike-next-auth/lib/adapter.ts
> +                method: "PUT",
I want to make all of them `PATCH`, but it doesn't work in the general case: https://github.com/chiselstrike/chiselstrike/issues/1845 Therefore, I use `PUT` everywhere.

2022-10-18 06:15 UTC, penberg commented on packages/chiselstrike-next-auth/lib/adapter.ts
> +    return toSession(sessions[0]);
It indeed does, but that's a general problem with consuming a ChiselStrike REST API so the fix should be in a client library, not this adapter.

2022-10-18 06:22 UTC, penberg commented
This is a rewrite, not an adaptation. The main difference is using `fetch()` directly as per outstanding review comments here: https://github.com/nextauthjs/next-auth/pull/4573#discussion_r906810184

(And as I mentioned you privately already, I started the rewrite because I couldn't get the adapter to run. But as it turns out, the problem was not in the original adapter, but the way I used `Credentials` provider, but now I already had 90% of the adapter rewritten.)

2022-10-18 06:24 UTC, penberg commented on packages/chiselstrike-next-auth/lib/adapter.ts
> +        async createUser(data) {
I just followed the style of the existing adapters that don't type them (don't know why). See, for example, https://github.com/nextauthjs/next-auth/blob/main/packages/adapter-firebase/src/index.ts.

2022-10-18 06:44 UTC, penberg commented
@dekimir You had bunch of comments on the documentation in `README.md` that I did not address, but I don't think are blocker for merging this.

To address the docs stuff, I think you, me, and @CodingDoug should sit down and figure out how to document this in `docs.chiselstrike.com` and then maybe replace the README with a link instead.

2022-10-18 09:45 UTC, haaawk commented on packages/chiselstrike-next-auth/lib/adapter.ts
> +    return {
Following methods are not expected by [the Adapter interface](https://next-auth.js.org/tutorials/creating-a-database-adapter#required-methods) but are present in this implementation: `getAccount`, `getSession`, `getVerificationToken`. What's the purpose of their existence?

2022-10-18 09:50 UTC, haaawk commented on packages/chiselstrike-next-auth/lib/adapter.ts
> +    return {
Adapter interface -> https://github.com/nextauthjs/next-auth/blob/main/packages/next-auth/src/adapters.ts#L79

2022-10-18 12:58 UTC, penberg commented on packages/chiselstrike-next-auth/lib/adapter.ts
> +    return {
The extra helpers are used by the tests. If you look at other adapters in the source tree, there's often a separate `Client` type that's used by the `Adapter`. I tried that route, but then our `Adapter` needs to wrap most of the `Client` methods, which is why I ended up with this.

2022-10-18 13:00 UTC, penberg commented on packages/chiselstrike-next-auth/lib/adapter.ts
> +    return {
@haaawk That `Adapter` type certainly makes sense, but it's defined in the `next-auth/adapters` AFAICT, which is not a public package. IOW, our external adapter cannot depend on it.

2022-10-18 13:17 UTC, haaawk commented on packages/chiselstrike-next-auth/lib/adapter.ts
> +    return {
Cool. Thanks for the explanation.

2022-10-18 22:55 UTC, dekimir commented on packages/chiselstrike-next-auth/lib/adapter.ts
> +                method: "PUT",
This isn't the general case (nor is the other PUT, for that matter).  This will overwrite existing fields that `updatedUser` omits, which is incorrect behaviour.

2022-10-18 23:14 UTC, dekimir commented
> This is a rewrite, not an adaptation.

I'm not sure a rewrite is justified when we already have working code.  What is your objection to using the adapter from the next-auth PR verbatim?  It contains better documentation, more tests, more error handling, and more code reuse.

> The main difference is using `fetch()` directly as per outstanding review comments here: [nextauthjs/next-auth#4573 (comment)](https://github.com/nextauthjs/next-auth/pull/4573#discussion_r906810184)

That comment was never properly justified.  Following it would make our adapter different from most others while duplicating a bunch of code (or merging another class into the adapter, not sure which; my clarifying questions were ignored).

2022-10-19 04:26 UTC, penberg commented on packages/chiselstrike-next-auth/lib/adapter.ts
> +                method: "PUT",
@dekimir Looking it again, you're right that the other `PUT` can also be replaced with `PATCH` (I guess the code was different at some point), so fixed.

2022-10-19 15:29 UTC, dekimir approved these changes
Approving to make progress on a long list of tasks awaiting us.  We'll need documentation and testing work anyway, whatever the difference between this PR and the next-auth PR.

2022-10-19 15:30 UTC, merged

2022-10-19 18:31 UTC, dekimir commented on packages/chiselstrike-next-auth/lib/adapter.ts
> +                method: "PUT",
On second thought, I'm wrong in claiming this is incorrect behaviour: this is exactly like PATCH due to the previous `Object.assign()` line.  Sorry.

2022-10-19 18:33 UTC, dekimir commented on packages/chiselstrike-next-auth/lib/adapter.ts
> +            const user = await fetchUserById(url, headers, updatedUser.id);
We probably don't need this fetch; PATCH will do the right thing all by itself, I suspect.